openapi: 3.0.3
info:
  title: MmmooOgle Feed API
  description: MmmooOgle Feed swagger API documentation
  contact: {}
  license: {}
  version: '1'
servers:
  - url: http://localhost:8080
    description: Inferred Url
tags:
  - name: report-external-applications-controller
    description: Report External Applications Controller
paths:
  /api/v1/external/feedingreeport:
    get:
      tags:
        - report-external-applications-controller
      summary: feedingReport
      operationId: feedingReportUsingGET
      parameters:
        - name: start_date
          in: query
          description: start_date
          required: true
          style: form
          schema:
            type: string
        - name: end_date
          in: query
          description: end_date
          required: true
          style: form
          schema:
            type: string
        - name: external_ration_id
          in: query
          description: external_ration_id
          required: true
          style: form
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeDailyReportExternalDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Static token:
            - global
  /api/v1/external/ration:
    post:
      tags:
        - report-external-applications-controller
      summary: importExternalRation
      operationId: importExternalRationUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ExternalRationRequestDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Static token:
            - global
components:
  schemas:
    ExternalRationIngredientRequestDTO:
      title: ExternalRationIngredientRequestDTO
      type: object
      properties:
        amountAsFed:
          type: number
          description: Amount as fed of ingredient in ration
          format: double
        amountDm:
          type: number
          description: Amount DM of ingredient in ration
          format: double
        costAsFed:
          type: number
          description: Cost of amount as fed of ingredient in ration
          format: double
        costDm:
          type: number
          description: Cost DM of ration ingredient
          format: double
          example: 41.25
        dm:
          type: number
          description: DM percentage of ration ingredient
          format: double
        externalId:
          type: integer
          description: >-
            ExternalId represent identification number of ration ingredient
            between systems
          format: int64
          example: 965
        feedName:
          type: string
          description: Name of ration ingredient
          example: Sojabohnen (gesch., Bioprofin)
        feedType:
          type: string
          description: Feed type of ingredient in ration
          example: >-
            Dry forage,Corn silage,Alfalfa silage, Grass silage, Other wet
            forage, By-productGrain ,Fatty acid source ,Triglycerides, Cp
            source, Rup source, Minerals, Miscellaneous, Vitamin, Premix,
            Forage, Concentrate, Commercial
        orderNumber:
          type: integer
          description: >-
            Order of ingredient in ration witch will be used as order of
            ingredient in mixer wagon
          format: int32
          example: 0
    ExternalRationRequestDTO:
      title: ExternalRationRequestDTO
      type: object
      properties:
        costDm:
          type: number
          description: Cost of DM per KG
          format: double
          example: 80.2
        dm:
          type: number
          description: DM (Dry meter) percentage of ration
          format: double
        externalId:
          type: string
          description: ExternalId represent identification number of ration between systems
          example: '856'
        rationIngredients:
          type: array
          items:
            $ref: '#/components/schemas/ExternalRationIngredientRequestDTO'
        rationName:
          type: string
          description: External ration name
          example: Ration Test 1
    FeedingLoadExternalDTO:
      title: FeedingLoadExternalDTO
      type: object
      properties:
        actualLoadedAmountKg:
          type: number
          description: Actual amount loaded in mixer wagon (unit = KG)
          format: double
          example: 1980
        amountPerLoadKg:
          type: number
          description: Amount that should be loaded in mixer wagon (unit = KG)
          format: double
          example: 2000
        id:
          type: integer
          description: Feeding load ID
          format: int64
          example: 452
        loadDetails:
          description: Loading details
          $ref: '#/components/schemas/LoadingDetailsExternalDTO'
        loadPosition:
          type: integer
          description: Feeding load position used for ordering feeding loads
          format: int64
          example: 0
        status:
          type: integer
          description: 'Feeding load status enum 0 = TO DO, 1 = IN PROGRESS , 2 = DONE '
          format: int32
          example: 0
        unloads:
          type: array
          description: Unloads from feeding load per pen
          items:
            $ref: '#/components/schemas/UnloadExternalDTO'
    FeedingLoadIngredientExternalDTO:
      title: FeedingLoadIngredientExternalDTO
      type: object
      properties:
        calculatedAmountKg:
          type: number
          description: Calculated amount of feed in feeding load (unit KG)
          format: double
          example: 780
        feedId:
          type: integer
          description: Feed ID
          format: int64
          example: 254
        feedName:
          type: string
          description: Feed name
          example: Alfalfa Meal, 17% CP
        id:
          type: integer
          description: Loading ID
          format: int64
        loadedAmountKg:
          type: number
          description: Actual amount of ingredient in feeding load (unit KG)
          format: double
          example: 750
    FeedingReportExternalDTO:
      title: FeedingReportExternalDTO
      type: object
      properties:
        feedingLoads:
          type: array
          description: Feeding loads for given feeding
          items:
            $ref: '#/components/schemas/FeedingLoadExternalDTO'
        feedingNumber:
          type: integer
          description: >-
            Feeding number enum value 1 = MORNING FEEDING , 2 = NOON FEEDING, 3
            = EVENING FEEDING
          format: int64
          example: 1
        id:
          type: integer
          description: Feeding ID
          format: int64
          example: 256
        pens:
          type: array
          description: Pens included in feeding
          items:
            $ref: '#/components/schemas/PenExternalDTO'
        status:
          type: integer
          description: Feeding status enum value 0 = TO DO , 1 = IN PROGRESS , 2 = DONE
          format: int32
          example: 0
    LoadingDetailsExternalDTO:
      title: LoadingDetailsExternalDTO
      type: object
      properties:
        endDate:
          type: string
          description: Loading finish date and time (UTC time)
          example: '2020-11-06T09:35:53Z'
        ingredients:
          type: array
          description: Loaded ingredients in mixer wagon
          items:
            $ref: '#/components/schemas/FeedingLoadIngredientExternalDTO'
        mixerWagon:
          description: Mixer wagon used for loading
          $ref: '#/components/schemas/MixerWagonExternalDTO'
        startDate:
          type: string
          description: Loading start date and time (UTC time)
          example: '2020-11-06T08:35:53Z'
    MixerWagonExternalDTO:
      title: MixerWagonExternalDTO
      type: object
      properties:
        id:
          type: integer
          description: Mixer wagon ID
          format: int64
          example: 478
        imageUrl:
          type: string
          description: Mixer wagon image url
        name:
          type: string
          description: Mixer wagon name
          example: USA x 15
        weight:
          type: number
          description: Loading start date and time (unit Tonnes)
          format: double
          example: 2
    PenExternalDTO:
      title: PenExternalDTO
      type: object
      properties:
        feedIntakePerAnimalKg:
          type: number
          description: Feed intake per animal (unit KG)
          format: double
        id:
          type: integer
          description: Pen ID
          format: int64
          example: 12
        numberOfAnimals:
          type: integer
          description: Number of animals in pen
          format: int32
          example: 100
        penName:
          type: string
          description: Pen name
          example: Test pen
    RecipeDailyReportExternalDTO:
      title: RecipeDailyReportExternalDTO
      type: object
      properties:
        feedingDate:
          type: string
          description: 'Feeding date '
          example: '2020-11-05'
        feedings:
          type: array
          description: Daily feedings for recipe
          items:
            $ref: '#/components/schemas/FeedingReportExternalDTO'
        herdId:
          type: integer
          description: Herd ID
          format: int64
          example: 245
        rationExternalId:
          type: integer
          description: ExternalId represent identification number of ration between systems
          format: int64
          example: 41933
        rationName:
          type: string
          description: Ration name
          example: Test ration
        recipeId:
          type: integer
          description: Recipe ID
          format: int64
          example: 421
        recipeName:
          type: string
          description: Recipe name
          example: Test recipe
        teamId:
          type: integer
          description: Team ID
          format: int64
          example: 542
    UnloadExternalDTO:
      title: UnloadExternalDTO
      type: object
      properties:
        endDate:
          type: string
          description: Unloading finish date and time (UTC time)
          example: '2020-11-06T09:35:53Z'
        id:
          type: integer
          description: Unload ID
          format: int64
          example: 5244
        penId:
          type: integer
          description: Pen ID
          format: int64
          example: 68
        startDate:
          type: string
          description: Unloading start date and time (UTC time)
          example: '2020-11-06T08:35:53Z'
        status:
          type: integer
          description: Unloading status enum 0 = TO DO 1 = IN PROGRESS 2 = DONE
          format: int32
          example: 0
        unloadedAmountKg:
          type: number
          description: Unloaded amount in pen from feeding load (unit KG)
          format: double
          example: 900
  securitySchemes:
    Static token:
      type: apiKey
      name: Static token
      in: header
